
export type CurrencyCode = 'USD' | 'AED' | 'AFN' | 'ALL' | 'AMD' | 'EUR' | 'ARS' | 'AUD' | 'AZN' | 'BAM' | 'BDT' | 'BGN' | 'BHD' | 'BIF' | 'BND' | 'BOB' | 'BRL' | 'BWP' | 'BYN' | 'CAD' | 'CDF' | 'CHF' | 'CLP' | 'CNY' | 'COP' | 'CRC' | 'CUP' | 'CVE' | 'CZK' | 'DJF' | 'DKK' | 'DOP' | 'DZD' | 'EGP' | 'ERN' | 'ETB' | 'FJD' | 'FKP' | 'GBP' | 'GEL' | 'GHS' | 'GIP' | 'GMD' | 'GNF' | 'GTQ' | 'GYD' | 'HKD' | 'HNL' | 'HRK' | 'HTG' | 'HUF' | 'IDR' | 'ILS' | 'INR' | 'IQD' | 'IRR' | 'ISK' | 'JMD' | 'JOD' | 'JPY' | 'KES' | 'KGS' | 'KHR' | 'KMF' | 'KPW' | 'KRW' | 'KWD' | 'KYD' | 'KZT' | 'LAK' | 'LBP' | 'LKR' | 'LRD' | 'LSL' | 'LYD' | 'MAD' | 'MDL' | 'MGA' | 'MKD' | 'MMK' | 'MNT' | 'MOP' | 'MRU' | 'MUR' | 'MVR' | 'MWK' | 'MXN' | 'MYR' | 'MZN' | 'NAD' | 'NGN' | 'NIO' | 'NOK' | 'NPR' | 'NZD' | 'OMR' | 'PAB' | 'PEN' | 'PGK' | 'PHP' | 'PKR' | 'PLN' | 'PYG' | 'QAR' | 'RON' | 'RSD' | 'RUB' | 'RWF' | 'SAR' | 'SBD' | 'SCR' | 'SDG' | 'SEK' | 'SGD' | 'SHP' | 'SLL' | 'SOS' | 'SRD' | 'SSP' | 'STN' | 'SYP' | 'SZL' | 'THB' | 'TJS' | 'TMT' | 'TND' | 'TOP' | 'TRY' | 'TTD' | 'TWD' | 'TZS' | 'UAH' | 'UGX' | 'UYU' | 'UZS' | 'VES' | 'VND' | 'VUV' | 'WST' | 'XAF' | 'XCD' | 'XOF' | 'XPF' | 'YER' | 'ZAR' | 'ZMW' | 'ZWL'

export const codes = new Map<CurrencyCode, string>([
  ['USD', 'United States Dollar; 10; 2'],
  ['AED', 'United Arab Emirates Dirham; 10; 2'],
  ['AFN', 'Afghan Afghani; 10; 2'],
  ['ALL', 'Albanian Lek; 10; 2'],
  ['AMD', 'Armenian Dram; 10; 2'],
  ['EUR', 'Euro; 10; 2'],
  ['ARS', 'Argentine Peso; 10; 2'],
  ['AUD', 'Australian Dollar; 10; 2'],
  ['AZN', 'Azerbaijani Manat; 10; 2'],
  ['BAM', 'Bosnia-Herzegovina Convertible Mark; 10; 2'],
  ['BDT', 'Bangladeshi Taka; 10; 2'],
  ['BGN', 'Bulgarian Lev; 10; 2'],
  ['BHD', 'Bahraini Dinar; 10; 3'],
  ['BIF', 'Burundian Franc; 10; 0'],
  ['BND', 'Brunei Dollar; 10; 2'],
  ['BOB', 'Bolivian Boliviano; 10; 2'],
  ['BRL', 'Brazilian Real; 10; 2'],
  ['BWP', 'Botswanan Pula; 10; 2'],
  ['BYN', 'Belarusian Ruble; 10; 2'],
  ['CAD', 'Canadian Dollar; 10; 2'],
  ['CDF', 'Congolese Franc; 10; 2'],
  ['CHF', 'Swiss Franc; 10; 2'],
  ['CLP', 'Chilean Peso; 10; 0'],
  ['CNY', 'Chinese Yuan; 10; 2'],
  ['COP', 'Colombian Peso; 10; 2'],
  ['CRC', 'Costa Rican Colón; 10; 2'],
  ['CUP', 'Cuban Peso; 10; 2'],
  ['CVE', 'Cape Verdean Escudo; 10; 2'],
  ['CZK', 'Czech Republic Koruna; 10; 2'],
  ['DJF', 'Djiboutian Franc; 10; 0'],
  ['DKK', 'Danish Krone; 10; 2'],
  ['DOP', 'Dominican Peso; 10; 2'],
  ['DZD', 'Algerian Dinar; 10; 2'],
  ['EGP', 'Egyptian Pound; 10; 2'],
  ['ERN', 'Eritrean Nakfa; 10; 2'],
  ['ETB', 'Ethiopian Birr; 10; 2'],
  ['FJD', 'Fijian Dollar; 10; 2'],
  ['FKP', 'Falkland Islands Pound; 10; 2'],
  ['GBP', 'British Pound Sterling; 10; 2'],
  ['GEL', 'Georgian Lari; 10; 2'],
  ['GHS', 'Ghanaian Cedi; 10; 2'],
  ['GIP', 'Gibraltar Pound; 10; 2'],
  ['GMD', 'Gambian Dalasi; 10; 2'],
  ['GNF', 'Guinean Franc; 10; 0'],
  ['GTQ', 'Guatemalan Quetzal; 10; 2'],
  ['GYD', 'Guyanaese Dollar; 10; 2'],
  ['HKD', 'Hong Kong Dollar; 10; 2'],
  ['HNL', 'Honduran Lempira; 10; 2'],
  ['HRK', 'Croatian Kuna; 10; 2'],
  ['HTG', 'Haitian Gourde; 10; 2'],
  ['HUF', 'Hungarian Forint; 10; 2'],
  ['IDR', 'Indonesian Rupiah; 10; 2'],
  ['ILS', 'Israeli New Sheqel; 10; 2'],
  ['INR', 'Indian Rupee; 10; 2'],
  ['IQD', 'Iraqi Dinar; 10; 3'],
  ['IRR', 'Iranian Rial; 10; 2'],
  ['ISK', 'Icelandic Króna; 10; 0'],
  ['JMD', 'Jamaican Dollar; 10; 2'],
  ['JOD', 'Jordanian Dinar; 10; 3'],
  ['JPY', 'Japanese Yen; 10; 0'],
  ['KES', 'Kenyan Shilling; 10; 2'],
  ['KGS', 'Kyrgystani Som; 10; 2'],
  ['KHR', 'Cambodian Riel; 10; 2'],
  ['KMF', 'Comorian Franc; 10; 0'],
  ['KPW', 'North Korean Won; 10; 2'],
  ['KRW', 'South Korean Won; 10; 0'],
  ['KWD', 'Kuwaiti Dinar; 10; 3'],
  ['KYD', 'Cayman Islands Dollar; 10; 2'],
  ['KZT', 'Kazakhstani Tenge; 10; 2'],
  ['LAK', 'Laotian Kip; 10; 2'],
  ['LBP', 'Lebanese Pound; 10; 2'],
  ['LKR', 'Sri Lankan Rupee; 10; 2'],
  ['LRD', 'Liberian Dollar; 10; 2'],
  ['LSL', 'Lesotho Loti; 10; 2'],
  ['LYD', 'Libyan Dinar; 10; 3'],
  ['MAD', 'Moroccan Dirham; 10; 2'],
  ['MDL', 'Moldovan Leu; 10; 2'],
  ['MGA', 'Malagasy Ariary; 10; 2'],
  ['MKD', 'Macedonian Denar; 10; 2'],
  ['MMK', 'Myanma Kyat; 10; 2'],
  ['MNT', 'Mongolian Tugrik; 10; 2'],
  ['MOP', 'Macanese Pataca; 10; 2'],
  ['MRU', 'Mauritanian Ouguiya; 10; 2'],
  ['MUR', 'Mauritian Rupee; 10; 2'],
  ['MVR', 'Maldivian Rufiyaa; 10; 2'],
  ['MWK', 'Malawian Kwacha; 10; 2'],
  ['MXN', 'Mexican Peso; 10; 2'],
  ['MYR', 'Malaysian Ringgit; 10; 2'],
  ['MZN', 'Mozambican Metical; 10; 2'],
  ['NAD', 'Namibian Dollar; 10; 2'],
  ['NGN', 'Nigerian Naira; 10; 2'],
  ['NIO', 'Nicaraguan Córdoba; 10; 2'],
  ['NOK', 'Norwegian Krone; 10; 2'],
  ['NPR', 'Nepalese Rupee; 10; 2'],
  ['NZD', 'New Zealand Dollar; 10; 2'],
  ['OMR', 'Omani Rial; 10; 3'],
  ['PAB', 'Panamanian Balboa; 10; 2'],
  ['PEN', 'Peruvian Nuevo Sol; 10; 2'],
  ['PGK', 'Papua New Guinean Kina; 10; 2'],
  ['PHP', 'Philippine Peso; 10; 2'],
  ['PKR', 'Pakistani Rupee; 10; 2'],
  ['PLN', 'Polish Zloty; 10; 2'],
  ['PYG', 'Paraguayan Guarani; 10; 0'],
  ['QAR', 'Qatari Rial; 10; 2'],
  ['RON', 'Romanian Leu; 10; 2'],
  ['RSD', 'Serbian Dinar; 10; 2'],
  ['RUB', 'Russian Ruble; 10; 2'],
  ['RWF', 'Rwandan Franc; 10; 0'],
  ['SAR', 'Saudi Riyal; 10; 2'],
  ['SBD', 'Solomon Islands Dollar; 10; 2'],
  ['SCR', 'Seychellois Rupee; 10; 2'],
  ['SDG', 'Sudanese Pound; 10; 2'],
  ['SEK', 'Swedish Krona; 10; 2'],
  ['SGD', 'Singapore Dollar; 10; 2'],
  ['SHP', 'Saint Helena Pound; 10; 2'],
  ['SLL', 'Sierra Leonean Leone; 10; 2'],
  ['SOS', 'Somali Shilling; 10; 2'],
  ['SRD', 'Surinamese Dollar; 10; 2'],
  ['SSP', 'South Sudanese Pound; 10; 2'],
  ['STN', 'São Tomé & Príncipe Dobra; 10; 2'],
  ['SYP', 'Syrian Pound; 10; 2'],
  ['SZL', 'Swazi Lilangeni; 10; 2'],
  ['THB', 'Thai Baht; 10; 2'],
  ['TJS', 'Tajikistani Somoni; 10; 2'],
  ['TMT', 'Turkmenistani Manat; 10; 2'],
  ['TND', 'Tunisian Dinar; 10; 3'],
  ['TOP', 'Tongan Paʻanga; 10; 2'],
  ['TRY', 'Turkish Lira; 10; 2'],
  ['TTD', 'Trinidad & Tobago Dollar; 10; 2'],
  ['TWD', 'New Taiwan Dollar; 10; 2'],
  ['TZS', 'Tanzanian Shilling; 10; 2'],
  ['UAH', 'Ukrainian Hryvnia; 10; 2'],
  ['UGX', 'Ugandan Shilling; 10; 0'],
  ['UYU', 'Uruguayan Peso; 10; 2'],
  ['UZS', 'Uzbekistani Som; 10; 2'],
  ['VES', 'Venezuelan Bolívar; 10; 2'],
  ['VND', 'Vietnamese Dong; 10; 0'],
  ['VUV', 'Vanuatu Vatu; 10; 0'],
  ['WST', 'Samoan Tala; 10; 2'],
  ['XAF', 'CFA Franc BEAC; 10; 0'],
  ['XCD', 'East Caribbean Dollar; 10; 2'],
  ['XOF', 'CFA Franc BCEAO; 10; 0'],
  ['XPF', 'CFP Franc; 10; 0'],
  ['YER', 'Yemeni Rial; 10; 2'],
  ['ZAR', 'South African Rand; 10; 2'],
  ['ZMW', 'Zambian Kwacha; 10; 2'],
  ['ZWL', 'Zimbabwean Dollar; 10; 2']
])
